### ISSUE TITLE
(x+1)/(x+1) not working correctly

### ISSUE THREAD

**Issue by Frivolimous** [davidedc/Algebrite#101]
Algebrite.run('(x+1)/(x+1)'); expected output: 1; actual output: 1/(x+1)+x/(x+1)

tested using dist/algebrite.bundle-for-browser.js at various versions.  Found a discrepancy where one test case worked in 1.1.2 but not in 1.2.0:

1.1.2 start: (x+1)/(x+1)(x-1) result: x + 1
1.2.0 start: (x+1)/(x+1)(x-1) result: 1/((1+x)(x-1))+x/(1+x)(x-1)

1.1.2 start: (x+1)/(x+1) result: 1 / (x + 1) + x / (x + 1)
1.2.0 start: (x+1)/(x+1) result: 1/(x+1)+x/(x+1)

1.1.2 start: (x-1)(x+1)/(x+1) result: -1 / (x + 1)
1.2.0 start: (x-1)(x+1)/(x+1) result: (-1+x)(x+1)/(x+1)

**Comment by davidedc** [comment]
Hi @Frivolimous can you wrap a simplify() around it and see if you are happy with that? (as discussed in https://github.com/davidedc/Algebrite/issues/89 )

the thing is... it's a complex matter whether Algebrite should automatically turn (x+1)/(x+1) into 1. 

For one, a "general" kind of simplification of rational expressions is (still) fairly expensive to do - so we could do that "automatically" in some special cases but not "in general".

Secondly, automatically turning (x+1)/(x+1) into 1 is slightly incorrect because the two quantities are not the same (for x = -1).

...just saying it could be a complex matter,,, I'd be happy on my part if "simplify" did the right thing.

closing in the meantime that you see whether "simplify" does what you want. If not, feel free to reopen.
