### ISSUE TITLE
Problem with log(2)

### ISSUE THREAD

**Issue by miketheanimal** [davidedc/Algebrite#26]
On the algebrite.org site, if I enter (using the Arbitrary-precision arithmetic box):

    log(1.99999999)
    log(2.0)
    log(2)
    log(2.00000001)
    log(3)
    sin(0)

then I get

    0.693147
    0.693147
    log(2)
    0.693147
    log(3)
    0

I get the same effect if I construct the equation programmaticly in JS. Looks like log isn't recognising 2 as a number?

**Comment by miketheanimal** [comment]
Follow up: I edited dist/algebrite.js and in yylog, immediately after the "isdouble" test I added:

    if (isrational(p1)) {
      d = Math.log(p1.q.a / p1.q.b);
      push_double(d);
      return;
    }

This fixes the problem :)

**Comment by miketheanimal** [comment]
sin(1) and cos(1) also exhibit the same problem .... same sort of isrational test in sine_of_angle and cosine_of_angle fixes these as well.

**Comment by davidedc** [comment]
Hi, sorry yes if that's convenient for you then great - the thinking though is that IF you enter a number as a float (with a dot) then you are OK with approximate numeric calculations coming out of it.

If you don't (say, instead of 0.1 you write 1/10 ), then the system will keep _perfect_ symbolic results.

UNLESS you use "float" like so: float(log(2)) - then it forces the numerical approximation.

So sin(0) works because it's a perfect result.

So the system sort of works as intended, but if you want to patch it to for your use (in a branch of yours) that's great too.

**Comment by miketheanimal** [comment]
Fair point. I've been able to change my code to work round this without patching algebrite. Thanx

**Comment by davidedc** [comment]
No probs by the way if you do things outside of the coverage of the existing tests, or anyways if you have the impression that you are doing tricky stuff, please let's add tests to cover those things, so I make sure I don't break them!
