### ISSUE TITLE
Matrix multiplication does not work for singular matrices (need to fix detection of pairs of inverse factors)

### ISSUE THREAD

**Issue by CesMak** [davidedc/Algebrite#56]
Hey,

Algebrite.dot("[[2,2],[2,2]]","[[0],[1]]").toString()  gives:
 Error: Stop: inverse of singular matrix

So this is actually not correct! 
any ideas how to solve that?

Best
Markus

**Comment by davidedc** [comment]
hmmm this is pretty bad. It comes from one of the calls to inv() in "inner.coffee".

Those calls are to detect when there is a multiplication of two factors that are one the inverse of the other, and hence simplify those away (or return identity).

So, weirdly, I do that by taking the inverse of one of the two factors, then subtract the two and check if zero.

I'm puzzled as to why I do that rather than just doing the multiplication and checking if it's the identity - I probably did that because I didn't have an identity-checking function ready and I thought I could get away with just using the available inv(), subtract(), and iszero(). Which obviously turned out to be a bad idea.

So I'd think that changing that should work... I might come around to this soon but I can't guarantee... If anyone wants to take a shot... (wink wink).

**Comment by davidedc** [comment]
just to be clear - the fix here would seem to be to do the test this way: execute the multiplication, then push the identity matrix, then do a subtraction, then check if zero. So this should all be feasible using standard available functions - unless there is something I'm missing.

**Comment by davidedc** [comment]
fixed in version 1.1.0 and 1.1.1

**Comment by davidedc** [comment]
specifically, here: https://github.com/davidedc/Algebrite/commit/ec9b056a09fd2045a07516ed3b16ecd8a0ea07e7
