### ISSUE TITLE
Algebrite incorrect results with node version > 10

### ISSUE THREAD

**Issue by Saikedo** [davidedc/Algebrite#78]
I just tried downloading Algebrite through npm and I noticed that it have a weird behaviour. For example on the npm version the following line of code.

`Algebrite.simplify("(x+3)^2").toString()`

produces the following output

"(x+3)^2"

The same code on Gitlab version(and in the sandbox on Algebrite.org) produces the following result.

"x^2+6*x+9".

I checked the versions and both versions are 1.2.0. Is it possible that a buggy build went out to npm and the repo was actually updated after that?

**Comment by davidedc** [comment]
Hi @Saikedo I looked into this briefly and I couldn't quite find the reason for this. I'm usually quite careful about versioning, however can't rule out some mismatch.

I checked the ```autoexpand``` flag and it's set in both cases. The website console runs the commands using Algebrite.run too, so that's also aligned. Also ```bake``` and ```test_flag``` seem the same.

Note that one gets the same behaviour without the simplification step.

It just seems that one one case there is automatic expansion and in the other case there isn't.

Are you getting other weird behaviours?

**Comment by davidedc** [comment]
just to clarify: I don't think this is down to "simplify" being broken. I'd rather thing this is due to automatic expansion happening in one case and not in the other,

**Comment by davidedc** [comment]
a simpler example that shows the difference is:
```
var Algebrite = require("algebrite")
console.log(Algebrite.run("(x+3)^2"));
```
(see: https://runkit.com/embed/blquyzinpawl )

**Comment by Saikedo** [comment]
That was the first thing that came to mind to be honest. I tried using the expand function but it seems like expand just does not do anything. Simplify at least works if there is no need for expansion but expand seems to always just return the string that you fed to it.

Note that I ended up pulling the version from here 

[http://algebrite.org/dist/latest-stable/algebrite.bundle-for-browser.js](url)

And it works just fine.

**Comment by davidedc** [comment]
@Saikedo be careful though, "expand" is not just "expansion", it does partial fraction expansion https://github.com/davidedc/Algebrite/blob/51d40342210d7b4dc574bc1a27fcf28613eb624c/sources/expand.coffee and https://github.com/davidedc/Algebrite/blob/51d40342210d7b4dc574bc1a27fcf28613eb624c/tests/expand.coffee

**Comment by davidedc** [comment]
if you observe other strange behaviour let me know as it might help finding the difference. Might have to step through both setups and find what the difference is.

**Comment by Saikedo** [comment]
@davidedc I actually switched to using the version that I mentioned above from now so I won`t be able to find any issues if I stick to that version. Please let me know if there is anything in particular that you might need me to test and I will be more than happy investigating it.

**Comment by davidedc** [comment]
@Saikedo riiiight so apparently it's due to node version.

v9.11.2 - correct: https://runkit.com/embed/6jrxj819jgd7
v10.15.1 and onward - incorrect: https://runkit.com/embed/blquyzinpawl

could you please tell me exactly how you got your result and which node version were you trying please?

**Comment by Saikedo** [comment]
So my node version is v11.8.0

I installed the Algebrite package by simply doing 

`npm i algebrite`

I then tried doing stuff like Algebrite.simplify((x+3)^2) and it does not work.
I suspected that this is due to expansion not working since Algebrite.simplify("x+x") and stuff like this work just fine. As expected Algebrite.expand((x+3)^2) did not work.

**Comment by davidedc** [comment]
@Saikedo  also things like ```Algebrite.factor("10!").toString();``` or ```Algebrite.factor("10^2").toString();``` don't work in the latest node versions. It's as if the ```^``` and ```!``` symbols are not working. I took a look at node release notes but nothing rings a bell. If you have any idea please let me know.

**Comment by davidedc** [comment]
more minimal interesting examples of what works and what doesn't
https://runkit.com/embed/7bu9jg0vgddp
```
var Algebrite = require("algebrite")
console.log(Algebrite.run("2^2"));
console.log(Algebrite.run("3!"));
console.log(Algebrite.run("float(2^2)"));
console.log(Algebrite.run("float(3!)"));
console.log(Algebrite.run("2^2.0"));
console.log(Algebrite.run("3.0!"));
```

gives

```
"2^2" // incorrect
"3!" // incorrect
"4.0"
"6.0"
"4.0"
"6"
```

**Comment by davidedc** [comment]
OK got it. node > v10.4.0 uses Javascript's BigInt. So Peter Olson's BigInteger.js becomes a thin wrapper around that native BigInt. The property "isSmall" of the native BigInt doesn't exist. Since I check that property in many places, all kinds of anomalies happen. See for example the screenshot below of the non-existent isSmall property being checked while doing ```3!```.

So what needs to be done is to transform that isSmall check into an appropriate check that works for native BigInt too.

Other needed changes might become apparent.

See https://developers.google.com/web/updates/2018/05/bigint for BigInt docs.

![bigintproblem](https://user-images.githubusercontent.com/769568/53523597-2255bc80-3ad5-11e9-9c90-48da22b884cd.PNG)

**Comment by Saikedo** [comment]
Ah, that makes total sense and such a pain in a butt to deal with :)

**Comment by davidedc** [comment]
OK I'm working on replacing Peter Olson's BigInteger.js with https://github.com/GoogleChromeLabs/jsbi

**Comment by davidedc** [comment]
done in version 1.2.1

**Comment by davidedc** [comment]
to check: https://runkit.com/embed/omx26z620h2l
