### ISSUE TITLE
Throws error in node version below 6 after 1.2.1 update

### ISSUE THREAD

**Issue by viktorstrate** [davidedc/Algebrite#82]
After updating Algebrite from v1.2.0 to v1.2.1, the tests for my project fails in Travis, for node version 4 and 5.

The tests does however pass successfully in node v6 and above.

Log highlight below, for full logs please see related Travis tests:
https://travis-ci.org/viktorstrate/algebra-latex/builds/515296883

```
/home/travis/build/viktorstrate/algebra-latex/node_modules/algebrite/dist/algebrite.js:962
    class rational {};
    ^^^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/viktorstrate/algebra-latex/node_modules
```

**Comment by davidedc** [comment]
Looked into this, so yes my best guess is that it's because I moved to using coffeescript v2 for generating the .js.

Coffeescript v1 targeted the previous JS version, the one without "class", so it didn't use JS "class" for classes (it did a "workaround").

Coffeescript v2 now targets the newer JS versions, the ones with "class", so it uses "class" directly.

Now those old node versions don't like that. So I see a couple of solutions (besides upgrading node obviously): 1) build yourself using coffeescript V1 for building (should work because I didn't use any specific coffeescript V2 features) or 2) use a transpiler to go from the JS with "class" to JS without it - something like the "babel" transpiler should do it.

How big of an impact is this for you? You have users/plans spanning that way back into node versions?

**Comment by davidedc** [comment]
thanks for supporting algebrite output with your project by the way

**Comment by viktorstrate** [comment]
I see, I will just stop supporting/testing the older versions of node for my project then, as it's is relaviley new, and it doesn't have a huge user base.
Most whose using is probably not using that old versions of node. And Algebrite is an optional dependency, so it should work without it.
