### ISSUE TITLE
1.0*10^(-7) is printed-out as 0.0

### ISSUE THREAD

**Issue by ibreaker14** [davidedc/Algebrite#85]
If I run Algebrite with a small number like `1.638802524798103e-39`, I get `0.0` back. Is there a way to preserve this number?

**Comment by davidedc** [comment]
this seems to be a printout issue, since
```
> 1.0*10^(-7) > 0.0
1
```

will look into this,

**Comment by davidedc** [comment]
yes so the problem is in here: https://github.com/davidedc/Algebrite/blob/6df074cdabac1a963b2ebdd09f0ff22a7f203d90/runtime/otherCFunctions.coffee#L29

yes so...
* printing "0.0" is misleading... something like "0.0000000..." would be slightly better. Note that if we print this out we also need to be able to parse this (and/or give an error/warning because of the truncation?)
* there should be an option somewhere to print more digits

**Comment by davidedc** [comment]
@ibreaker14 in the latest master build you can now do:
```
> forceFixedPrintout=0

> 1.0*10^(-15)
1*10^(-15)
```

... I might change the last output to be:
```
1.0*10^(-15)
```
I'll think about it a bit more, Anyways pending that detail, this is the fix.
You can either disable the forcing of the fixed notation, or if you want to keep the fixed notation you can set the minimum number by doing
```
maxFixedPrintoutDigits=20
```

very long fixed notations are awkward though, you probably want to just
```
forceFixedPrintout=0
```

so you get the standard scientific-notation printout.
